name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    name: Lint HTML & CSS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Linting Tools
        run: |
          npm install -g htmlhint stylelint stylelint-config-standard

      - name: Run HTML Linter
        run: |
          htmlhint "src/**/*.html"

      - name: Run CSS Linter
        run: |
          stylelint "styles/**/*.css"

  build:
    name: Build Static Website
    runs-on: ubuntu-latest
    needs: linting

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Parcel
        run: |
          npm install -g parcel-bundler

      - name: Build Website
        run: |
          parcel build src/index.html --no-optimize --public-url ./
